Repository EmilyFrade/mini-asaas, pull requests merged in 2024-06, with the labels that each got.

#53 Corrige bug no selection-card da 1ª etapa do cadastro de Customer
  grails-app/views/customer/templates/_step-one.gsp
Labels: bug

#52 Implementar serviço de envio de e-mail
  .env.example
  build.gradle
  grails-app/conf/application.yml
  grails-app/conf/spring/resources.groovy
  grails-app/services/com/mini/asaas/email/SendGridEmailService.groovy
  src/main/groovy/com/mini/asaas/email/EmailAdapter.groovy
  src/main/groovy/com/mini/asaas/email/EmailService.groovy
Labels: dependência

#55 Corrigir bug no preenchimento automático do campo estado através do CEP
  grails-app/views/templates/_address-group.gsp
Labels: bug

#48 Implementar relacionamento (1:n) entre as entidades Customer e User
  .env.example
  grails-app/conf/application.yml
  grails-app/controllers/com/mini/asaas/customer/CustomerController.groovy
  grails-app/controllers/com/mini/asaas/user/UserController.groovy
  grails-app/domain/com/mini/asaas/user/User.groovy
  grails-app/init/com/mini/asaas/BootStrap.groovy
  grails-app/services/com/mini/asaas/customer/CustomerService.groovy
  grails-app/services/com/mini/asaas/user/UserService.groovy
  grails-app/views/customer/templates/_step-two.gsp
  src/main/groovy/com/mini/asaas/base/BasePerson.groovy
  src/main/groovy/com/mini/asaas/customer/CustomerValidator.groovy
  src/main/groovy/com/mini/asaas/user/UserRepository.groovy
  src/main/groovy/com/mini/asaas/user/UserValidator.groovy
  src/main/groovy/com/mini/asaas/user/adapters/SaveUserAdapter.groovy
Labels: aguardando-outro-pr

#46 Implementar fluxo de atualizar senha de um usuário
  grails-app/controllers/com/mini/asaas/user/UserController.groovy
  grails-app/services/com/mini/asaas/user/UserService.groovy
  grails-app/views/user/show.gsp
  src/main/groovy/com/mini/asaas/user/UserValidator.groovy
  src/main/groovy/com/mini/asaas/user/adapters/UpdateUserPasswordAdapter.groovy
Labels: aguardando-outro-pr

#54 Implementar vencimento automático de cobrança por meio de Job
  build.gradle
  grails-app/conf/application.yml
  grails-app/jobs/com/mini/asaas/OverduePaymentsJob.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  src/main/groovy/com/mini/asaas/payment/PaymentRepository.groovy
  src/main/groovy/com/mini/asaas/utils/DateFormatUtils.groovy
Labels: dependência

#58 Implementar tela de listagem de notificações (Front-End)
  grails-app/taglib/com/mini/asaas/NotificationTagLib.groovy
  grails-app/views/layouts/main.gsp
  grails-app/views/notification/_notification-card.gsp
  grails-app/views/notification/_notifications-dropdown.gsp
  src/main/groovy/com/mini/asaas/atlas/AtlasIcon.groovy
  src/main/groovy/com/mini/asaas/atlas/AtlasTheme.groovy
Labels: aguardando-outro-pr

#60 Implementar visualização de recibos de pagamento
  grails-app/assets/stylesheets/payment/receipt.css
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/domain/com/mini/asaas/payment/Payment.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  grails-app/views/payment/receipt.gsp
  grails-app/views/payment/show.gsp
  src/main/groovy/com/mini/asaas/utils/DateFormatUtils.groovy
Labels: aguardando-outro-pr

#66 Implementar funcionalidade de atualizar senha de um usuário
  grails-app/controllers/com/mini/asaas/user/UserController.groovy
  grails-app/services/com/mini/asaas/user/UserService.groovy
  grails-app/views/user/show.gsp
  src/main/groovy/com/mini/asaas/user/UserValidator.groovy
  src/main/groovy/com/mini/asaas/user/adapters/UpdateUserPasswordAdapter.groovy
Labels: aguardando-outro-pr

#69 [FIX] Remove importação de NotificationLink, que não existe mais
  src/main/groovy/com/mini/asaas/notification/NotificationAdapter.groovy
Labels: bug, importante

#71 Adicionar disparo de emails nos eventos necessários relacionados à cobrança
  .env.example
  grails-app/services/com/mini/asaas/payment/PaymentEventNotificationService.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  grails-app/views/payment/templates/email/_payment-created.gsp
  grails-app/views/payment/templates/email/_payment-deleted.gsp
  grails-app/views/payment/templates/email/_payment-overdue.gsp
  grails-app/views/payment/templates/email/_payment-received.gsp
Labels: aguardando-outro-pr

#74 Corrigir select de pagadores vazio após algum erro ao tentar cadastrar uma nova cobrança
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
Labels: bug
