Repository EmilyFrade/mini-asaas, pull requests merged in 2024-05, with the labels that each got.

#12 Consolidar o fluxo de um endereço (`Address`)
  src/main/groovy/com/mini/asaas/base/BasePerson.groovy
  src/main/groovy/com/mini/asaas/enums/address/AddressState.groovy
  src/main/groovy/com/mini/asaas/utils/ZipCodeUtils.groovy
Labels: aguardando-outro-pr

#16 Adicionar template para Pull Requests
  .github/pull_request_template.md
Labels: documentação

#14 Corrigir a configuração de campos com valores únicos em `BasePerson`
  src/main/groovy/com/mini/asaas/base/BasePerson.groovy
Labels: aguardando-outro-pr

#18 Corrigir erro relacionado à constraint de valor padrão em `BasePerson`
  src/main/groovy/com/mini/asaas/base/BasePerson.groovy
Labels: bug

#22 Adicionar métodos para eliminar espaços iniciais e finais de uma string
  src/main/groovy/com/mini/asaas/utils/StringUtils.groovy
  src/main/groovy/com/mini/asaas/utils/Utils.groovy
  src/test/groovy/com/mini/asaas/utils/StringUtilsTest.groovy
  src/test/groovy/com/mini/asaas/utils/UtilsTest.groovy
Labels: aguardando-outro-pr

#20 Implementar a Classe de Domínio `Customer`
  grails-app/domain/com/mini/asaas/customer/Customer.groovy
  grails-app/i18n/messages.properties
  src/main/groovy/com/mini/asaas/base/BasePerson.groovy
  src/main/groovy/com/mini/asaas/customer/CompanyType.groovy
  src/main/groovy/com/mini/asaas/customer/CustomerAdapter.groovy
  src/main/groovy/com/mini/asaas/enums/PersonType.groovy
  src/main/groovy/com/mini/asaas/enums/address/AddressState.groovy
  src/main/groovy/com/mini/asaas/utils/CpfCnpjUtils.groovy
  src/main/groovy/com/mini/asaas/utils/DateFormatUtils.groovy
  src/main/groovy/com/mini/asaas/utils/StringUtils.groovy
  src/test/groovy/com/mini/asaas/customer/CustomerAdapterTest.groovy
  src/test/groovy/com/mini/asaas/utils/DateFormatUtilsTest.groovy
Labels: aguardando-outro-pr

#25 Implementa layouts de estilo para o projeto
  grails-app/views/layouts/main.gsp
  grails-app/views/utils/_sidebar.gsp
Labels: style

#26 Implementar criação do controller e das views de um Payer
  grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
  grails-app/views/payer/create.gsp
  grails-app/views/payer/index.gsp
  grails-app/views/payer/show.gsp
  src/main/groovy/com/mini/asaas/enums/AlertType.groovy
Labels: aguardando-outro-pr

#6 Adicionar Spring Security como dependência do projeto.
  build.gradle
  grails-app/conf/application.groovy
  grails-app/conf/spring/resources.groovy
  grails-app/domain/com/mini/asaas/user/Role.groovy
  grails-app/domain/com/mini/asaas/user/User.groovy
  grails-app/domain/com/mini/asaas/user/UserRole.groovy
  grails-app/init/com/mini/asaas/BootStrap.groovy
  src/main/groovy/com/mini/asaas/user/UserPasswordEncoderListener.groovy
Labels: dependência, spring-security

#8 Implementar fluxo de login com spring security
  .env.example
  grails-app/conf/application.groovy
  grails-app/conf/application.yml
  grails-app/controllers/com/mini/asaas/user/AuthController.groovy
  grails-app/controllers/com/mini/asaas/user/UserController.groovy
  grails-app/domain/com/mini/asaas/user/User.groovy
  grails-app/i18n/messages.properties
  grails-app/init/com/mini/asaas/BootStrap.groovy
  grails-app/services/com/mini/asaas/user/UserService.groovy
  grails-app/views/auth/login.gsp
  grails-app/views/user/show.gsp
  src/main/groovy/com/mini/asaas/repository/UserRepository.groovy
  src/main/groovy/com/mini/asaas/user/LoginUserAdapter.groovy
  src/main/groovy/com/mini/asaas/user/UserAdapter.groovy
  src/main/groovy/com/mini/asaas/user/UserPasswordEncoderListener.groovy
Labels: spring-security

#10 Atualizar a view de login para usar o design system atlas.
  grails-app/assets/images/asaas-white.svg
  grails-app/assets/images/close-icon.svg
  grails-app/assets/images/login-asaas-preview.png
  grails-app/assets/stylesheets/auth/login.css
  grails-app/views/auth/login.gsp
  grails-app/views/layouts/auth.gsp
Labels: aguardando-outro-pr, spring-security

#34 Possibilitar acessar pagador em caso de CPF-CNPJ/email igual
  grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
  grails-app/i18n/messages.properties
  grails-app/services/com/mini/asaas/payer/PayerService.groovy
  grails-app/views/payer/create.gsp
  grails-app/views/payer/restore.gsp
  grails-app/views/payer/show.gsp
  src/main/groovy/com/mini/asaas/exceptions/BusinessException.groovy
  src/main/groovy/com/mini/asaas/payer/PayerValidator.groovy
Labels: aguardando-outro-pr
